//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public hotel()
        {
            this.comments = new HashSet<comment>();
            this.rooms = new HashSet<room>();
            this.options = new HashSet<option>();
        }
    
        public int hotel_id { get; set; }
        public string hotel_name { get; set; }
        public int stars { get; set; }
        public string rib { get; set; }
        public Nullable<int> city_id { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<room> rooms { get; set; }
        public virtual ml_testing_data ml_testing_data { get; set; }
        public virtual ml_training_data ml_training_data { get; set; }
        public virtual ICollection<option> options { get; set; }
    }
}
