//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_testing_data
    {
        public int hotel_id { get; set; }
        public string comment_str { get; set; }
        public int rating { get; set; }
    
        public virtual hotel hotel { get; set; }
    }
}
