//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public reservation()
        {
            this.rooms_reservation = new HashSet<rooms_reservation>();
        }
    
        public int reservation_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public System.DateTime arrival_date { get; set; }
        public System.DateTime departure_date { get; set; }
        public string reservation_status { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<rooms_reservation> rooms_reservation { get; set; }
    }
}
