//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public room()
        {
            this.rooms_reservation = new HashSet<rooms_reservation>();
        }
    
        public int room_id { get; set; }
        public Nullable<int> hotel_id { get; set; }
        public string room_type { get; set; }
        public double price { get; set; }
        public int sheet_count { get; set; }
        public bool extra_bed { get; set; }
        public int rooms_count { get; set; }
    
        public virtual hotel hotel { get; set; }
        public virtual ICollection<rooms_reservation> rooms_reservation { get; set; }
    }
}
