//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rooms_reservation
    {
        public int reservation_id { get; set; }
        public int room_id { get; set; }
        public int reserved_rooms_count { get; set; }
    
        public virtual reservation reservation { get; set; }
        public virtual room room { get; set; }
    }
}
